import datetime,hashlib,json,pathlib
from build import ROOT,OUT,CUTOFF,EXPOSURE,REGIMES,ROWS,SOURCES
D=lambda name,obj:(OUT/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
log={'information_as_of':CUTOFF,'external_cost_usd':'unmetered','external_model_calls':'unmetered','workflow_usage_numeric_zeros':'Placeholders, not measurements of zero activity or cost.','web_run_calls':7,'search_query_count':2,'timestamp_note':'Post-retrieval clock checkpoints; for batched reads, retrieval upper bounds. Exact network response times were not metered.','exposure':EXPOSURE,'calls':[
{'call':1,'checkpoint':'2026-09-16T01:19:13+00:00','operations':['open https://www.federalreserve.gov/monetarypolicy/openmarket.htm','open https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm'],'summary':'Official change history ends December 2025; calendar supplies all 2026 scheduled dates and statements through July.','access_failures':[]},
{'call':2,'checkpoint':'2026-09-16T01:19:13+00:00','operations':['click January, March, April, June and July 2026 HTML statements from FOMC calendar'],'summary':'Baseline and all elapsed scheduled decisions maintained the target range at 3.50–3.75%. Dissent shifted from cuts early in year to hikes in July.','access_failures':[]},
{'call':3,'checkpoint':'2026-09-16T01:19:19+00:00','operations':['open https://www.federalreserve.gov/newsevents/2026-press-monetary.htm','open https://www.bls.gov/news.release/empsit.nr0.htm','open https://www.bls.gov/news.release/cpi.nr0.htm','open https://www.bea.gov/news/2026/personal-income-and-outlays-july-2026'],'summary':'August jobs showed a stronger month after weak hiring; CPI and PCE pages accessed, relevant paragraphs expanded next call.','access_failures':[{'url':'https://www.federalreserve.gov/newsevents/2026-press-monetary.htm','error':'web.run internal error: URL not safe to open, non-retryable','resolution':'Used valid official general press-release archive discovered subsequently.'}]},
{'call':4,'checkpoint':'2026-09-16T01:19:28+00:00','operations':['open relevant lines of CPI and PCE pages','open https://www.federalreserve.gov/newsevents/pressreleases.htm','open https://www.federalreserve.gov/monetarypolicy/fomcminutes20260729.htm'],'summary':'Reviewed headline/core monthly and annual inflation. General press page and July minutes returned metadata; detailed minutes not used in forecast. No probabilities shown in inspected return.','access_failures':[]},
{'call':5,'checkpoint':'2026-09-16T01:19:54+00:00','operations':[{'search':'site:federalreserve.gov/newsevents/pressreleases/ 2026 "lower" "target range" -"2025" -"2024"','domains':['federalreserve.gov']},{'search':'site:federalreserve.gov/newsevents/pressreleases/ 2026 August September federal funds target range','domains':['federalreserve.gov']},'open general press release page'],'summary':'Search for missed emergency cuts found held ranges, official dissents, discount-rate minutes, July report and valid 2026 archive. Some 2024/2025 snippets appeared despite query terms; excluded from current-state assessment. Search absence is not proof of absence.','access_failures':[]},
{'call':6,'checkpoint':'2026-09-16T01:19:54+00:00','operations':['open https://www.federalreserve.gov/newsevents/pressreleases/2026-press.htm','open https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm','open https://www.federalreserve.gov/monetarypolicy/2026-07-mpr-summary.htm'],'summary':'Archive lists through September 11 with no newly found cut, but omits some known FOMC statement entries; report confirms unchanged range since year start. Chair speech opened for current policy stance.','access_failures':[]},
{'call':7,'checkpoint':CUTOFF,'operations':['find Current and inflation in Warsh speech','find since in July monetary policy report','open Warsh speech around line 103'],'summary':'Chair regards labor as near full employment and inflation as principal concern; summer improvement did not establish trend confidence. Incidental qualitative reference to inflation swaps and market expectations disclosed; no numeric prices or event probabilities.','access_failures':[]}], 'sources_used':[{'id':i,'url':url,'retrieved_at':t,'summary':claim,'limit':limit} for i,url,title,t,pub,claim,limit in SOURCES]}
D('source_query_log.json',log)
f=json.loads((OUT/'forecast.json').read_text());a=json.loads((OUT/'analysis.json').read_text());s=json.loads((OUT/'sensitivity.json').read_text())
lines=['# Federal Reserve cut: independent paper forecast','',f"**Estimate: {a['probability']:.0%} YES.** Prospective, information cutoff **{CUTOFF}** (September 15, 2026, US Eastern).",'',f"Forecast ID: `{f['forecast_id']}`. No market-event probabilities or prices were used.",'','## Exact event and eligibility','','At least one FOMC announcement reducing its target federal funds range between February 26 and December 31, 2026. A cut after a hike counts; discount-rate adjustments and dissents favoring a cut do not. Deadline is January 1, 2027 at 00:00 Eastern, exclusive.','', 'The January baseline and March 18, April 29, June 17 and July 29 statements all show 3.50–3.75% holds. The July report confirms the range was maintained since year start. No unscheduled qualifying cut was found in supplementary official indexes. The question is eligible; it is not already known. The historical change table is stale and the general release index omits some scheduled statements, so neither absence alone was treated as decisive.','', '## Scenario partition','','Every path belongs to one dominant regime, in priority order: acute disruption, material labor deterioration, material disinflation, then persistence. Within regimes, branches identify the first qualifying cut or no cut in the window. These are subjective joint weights, not independently sampled events.','', '| Joint scenario | Weight | First cut / outcome |','|---|---:|---|']
for row,sc in zip(ROWS,json.loads((OUT/'model.json').read_text())['scenarios']):lines.append(f"| {row[0]} | {sc['weight']:.1%} | {row[3]} |")
lines+=['', 'The emergency branch date is a representative of any first unscheduled cut before expiry. `never` means no cut within this contract, not no cut forever. Scheduled announcement times are modeling assumptions on observed meeting dates.','', '## Drivers and contrary evidence','','The July decision had three dissents favoring a hike. Chairman Warsh emphasized inflation in August. July core PCE remained 3.3% annually, favoring continued restraint. Against that, annual core CPI eased to 2.4%, June/July job gains were weak, and July real consumption was nearly flat. August payroll growth and stable unemployment resist an immediate downturn interpretation. Core CPI and PCE differ in coverage and weights; their rates are not interchangeable.','', '## Subjective sensitivity','','Baseline regime weights are persistence 58%, disinflation 25%, labor deterioration 12%, and acute shock 5%. Within-regime probabilities of a qualifying cut are respectively 0%, 48%, 50%, and 60%; these are judgments, not fitted frequencies.','', '| Weight stress | Result |','|---|---:|']
for c in s['subjective_regime_weight_stress']: lines.append(f"| {c['name']} | {c['probability']:.1%} |")
lines+=['','Halving within-regime easing responses gives 10.5%. Raising those responses to 70%, 75% and 80% for disinflation, labor and shock gives 30.5%. Moving all December-success paths into January gives 9%. These are stress tests, not confidence intervals.','', '## Review, triggers and limits','','Review challenged the estimate both upward and downward and retained the model-derived result. Main triggers: September 16 FOMC announcement; any emergency reduction; new CPI/PCE and employment evidence; material financial disruption. Any qualifying announcement makes this already known and ends prospective forecasting of this window.','','This is a small paper pilot, not a calibrated macroeconomic model. Procedural completeness does not establish predictive accuracy. The timeline engine evaluates supplied assumptions; it does not infer them from evidence. No starting probability was supplied. The original unweighted structure, post-research refinement, workflow clone, parameter revision and final weighted version remain preserved.','','External costs and model calls are **unmetered**. Numeric zeros in package usage fields are placeholders. Seven web calls, including two search queries, are documented. One incorrect official archive URL failed; a valid official archive was used. The Chair speech incidentally mentioned qualitative inflation-market expectations, but no event probabilities or numeric market prices were seen.','','## Sources','']
for i,url,title,t,pub,claim,limit in SOURCES: lines.append(f"- [{title}]({url}) — {claim}")
lines+=['','## Reproduce','','Run `PYTHONPATH=src python3 build.py` from this workspace to verify the saved analysis and dates without reissuing or changing the sealed record. `--issue` refuses to overwrite the existing project. The database is in `project/.vorhersage`; `forecast.html` is the offline export. Source evidence consists of short paraphrases, not full page archives.','']
(OUT/'forecast_summary.md').write_text('\n'.join(lines))
D('usage.json',{'cost_usd':'unmetered','model_calls':'unmetered','web_run_calls':7,'search_queries':2,'workflow_numeric_zeros':'placeholders'})
print('Summary, source log and usage labels written.')
